### ISSUE TITLE
Incompatability crash With Possibly Waila or Walwla

### ISSUE THREAD

**Issue by Azzanine** [CovertJaguar/Timberjack#11]
Possible crash with the two aforementioned mods.

Not entirely sure if this is your problem as removing said mods prevents crash.

Crash occurs when you try to fell a tree, soon as all the tree bits fly bam, it crashes.

Crash log below

[Pastebin](https://pastebin.com/Ni2HmRUW)

**Comment by CovertJaguar** [comment]
They are probably calling the entity NBT functions on the client side, which it isn't really setup for atm.

**Comment by ElvenChaos** [comment]
What is the plan for getting this fix to players?

**Comment by SvEgiiVEteR** [comment]
and me 1.10.2
https://gist.github.com/36d3114889f5e616135fe8a549590f71

**Comment by Liiw** [comment]
Well, it seems to be working with the previous 1.10.2 version, so I'm currently reverting back to that one.
