### ISSUE TITLE
Leaves?

### ISSUE THREAD

**Issue by CMCarlsen** [CovertJaguar/Timberjack#16]
This is definitely a suggestion more than a "bug", but -

Would it be possible to deal with the over-kill leaf physics/splash in some way?

I really love this mod, I've been looking for something to replace the "vein miner"-ish type lumbering options, and this was perfectly up my alley. However, my one major complaint is that when logging trees that are in relatively close proximity to one another, the tree being felled, err... "steals"?... all of the leaves off any surrounding trees.

I'm presuming (as I honestly have no idea how this is implemented) that Timberjack somehow recursively looks for leaf blocks and just yanks along any that it finds. While I wouldn't necessarily qualify this as a bug, it's definitely something I would love to see improved?

I'm happy to offer any suggestions/advice I can think of, but I guess I first wanted to see if you were even open to the idea.

Thanks!
-Celtic

**Comment by CovertJaguar** [comment]
If you can think of a better solution, I'm open to hearing it. As far as I know there isn't one. There is nothing other than proximity that ties any leaf block to a specific log.

**Comment by CMCarlsen** [comment]
I apologize.

I haven't forgotten about this, I've just been particularly busy with class as of this last week or so. Mid-terms and such.

I'd love to chat more about this. Do you have any particular IRCs or other chat channels you frequent that you'd be willing to discuss this in? I'd be happy to formally write up a suggestion here afterward if something came of our chat.

Understand if not though. Sure you got your own life going on too. =P

Lemme know!
-Celtic
