### ISSUE TITLE
[Suggestion] Directed tree felling

### ISSUE THREAD

**Issue by Liiw** [CovertJaguar/Timberjack#3]
Hello!

I love the mod, it adds nice immersion to treecutting. However there is something that I would like to see implemented, if possible.

**Directed tree felling.** 

Currently when chopping the tree, it randomly falls apart around it's base. Would it be possible to make the tree "fall over" in a certain direction, much like it works in reality? Perhaps it could also take into account the direction from where the player is standing and falls to the opposite side. It doesn't have to retain it's whole structure, maybe after hitting the ground, the branches could also "even off" to the ground, or then again maybe it would be cooler if they didn't. Furthermore, after falling over, the logs would be turned horizontal.

Please let me know what you think about this idea.

**Comment by CovertJaguar** [comment]
I had originally intended it to be like that, but despite my best efforts the game's physics would not cooperate.

I could get 1x1 trunks to fall in a certain direction easily enough, but it did not scale up at all. Any large trunks behaved extremely oddly. Usually the the trunk would split in two and move in opposite directions, and remain standing.

I eventually abandoned any hope of getting it to work properly.

Additionally, there is no standard method to rotate logs. I could rotate vanilla logs, but mod logs use a variety of different rotation parameters. It might be possible to use the Block.rotateBlock() method, I'll have to investigate.

**Comment by liach** [comment]
Adding an entity tick listener might fix this.

**Comment by liach** [comment]
Or adding an initial motion may fix this too.

**Comment by CovertJaguar** [comment]
It won't.
