### ISSUE TITLE
Falling blocks getting stuck.

### ISSUE THREAD

**Issue by Claycorp** [CovertJaguar/Timberjack#6]
Falling blocks get stuck quite often. sometimes its not really that big of a deal to clean up but other times it means ripping out a large section of whatever to get rid of the blocks as they never despawn, block placing of other blocks and mess up trying to hit things.

Could a config be added to enable/disable decaying of these blocks?

**Comment by CovertJaguar** [comment]
It seems to be a bug in the vanilla Falling Entity update code. I plan on implementing my own version of the Falling Entity to fix this and other issues.

Protip: Hooking them with Fishing Poles seem to cause them to despawn.

**Comment by Claycorp** [comment]
Just as a follow up with it on a server, After a week of play we had ~800 leaves stuck, with an average of 3-5 players on over the whole week. I am for sure looking forward to the improved leaves. For now we are going to combat it with a command block on a timer to kill them off.

EDIT: Most people actively removed as many leaves as they could, so that number would have been way higher.

**Comment by CovertJaguar** [comment]
Yeah, we are having the same problem on our server. We applied the same solution.

I'll try and get the custom entity finished and tested sometime this week. And I'll add some code to hunt down and kill the old entities.

**Comment by CovertJaguar** [comment]
Fixed by 968bbb2b512ef0b48d4c2155736412b5a1bd6b9c
